<tr bgcolor=white>
                                  <td>{{$no++}}</td>
                                  <td>{{$data_rekap->user->detail->nama}}</td>
                                  <td>{{$data_rekap->user->detail->jabatan->name}}</td>
                                  <td>{{rupiah($data_rekap->gaji_pokok)}}</td>
                                  <td>{{rupiah($data_rekap->tunjab)}}</td>
                                  <td>{{rupiah($data_rekap->uang_transport)}}</td>
                                  <td>{{rupiah($data_rekap->uang_makan)}}</td>
                                  <td>{{rupiah($tunkel)}}</td>
                                  <td>{{rupiah($gaji_total)}}</td>
                                  <td>{{rupiah($data_rekap->p_kasbon)}}</td>
                                  <td>{{rupiah($data_rekap->p_angs)}}</td>
                                  <td>{{rupiah($data_rekap->p_simwa)}}</td>
                                  <td>{{rupiah($data_rekap->p_bpjs)}}</td>
                                  <td>{{rupiah($data_rekap->p_arisan)}}</td>
                                  <td>{{rupiah($lainnya)}}</td>
                                  <td>{{rupiah($zis)}}</td>
                                  <td>{{rupiah($jml_pot)}}</td>
                                  <td>{{rupiah($jml_diterima)}}</td>
                                </tr>